version: "3.9"

services:
  client:
    container_name: client
    build: ./client
    ports:
      - "80:80"
  server:
    container_name: server
    build: ./server
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    
    environment:
      POSTGRES_DB: "todo_calendar"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

    